_target_: src.models.mvit_module.MVITLitModule

freeze_layers: False
output_size: 1
pos_weight: 2
lr: 0.00005
weight_decay: 0.005
lr_scheduler_min_lr: 6.25e-5
lr_scheduler_factor: 0.5
lr_scheduler_patience: 15
