_target_: src.datamodules.mvit_datamodule.MViTDataModule

train_path: "/hkfs/work/workspace/scratch/im9193-H5/data/train.csv"
val_path: "/hkfs/work/workspace/scratch/im9193-H5/data/valid.csv"
img_dir: "/hkfs/work/workspace/scratch/im9193-H5/data/imgs/"
batch_size: 64
num_workers: 0
pin_memory: False
